### ISSUE TITLE
unknown html tags not indented

### ISSUE THREAD

**Issue by bartels** [othree/html5.vim#51]
Using a custom html tag breaks indentation.

For example:

```
<html>
    <body>

        <section
            id="some-id"
            class="some-class"></section>

        <custom-tag
            id="another-id"
            class="another-class"></custom-tag>

    </body>
</html>
```

Now `gg=G` will unindent the id & class attributes on `custom-tag`.  The indentation is also initially wrong if you "open" `custom-tag` to edit inside.

I can see  custom tag names like this becoming widespread as web components get more usage.

**Comment by asoltys** [comment]
I was disappointed to find this issue closed with no solution but ended up finding this patched indent file that seems to do the trick: https://github.com/mgiuffrida/vim2/blob/patch-1/runtime/indent/html.vim

**Comment by othree** [comment]
There are more discussion spread in different issue.
But people reported the one vim built-in have some issue.
So I rollback the change.

And there is another PR now <https://github.com/othree/html5.vim/pull/71/files>
But I don't have enough time to look and test.
