### ISSUE TITLE
Indent Global Variable Documentation

### ISSUE THREAD

**Issue by amadeus** [othree/html5.vim#55]
In the indent file there is a reference to 2 global variables:

```
" let g:html_indent_tags = 'html\|p\|time'
" let g:html_exclude_tags = ['html', 'style', 'script', 'body']
```

It's not documented anywhere what exactly they are used for, and looking through the source it wasn't clear either.

If you have a moment, could you provide some insight please?

**Comment by othree** [comment]
It's from codes I based on.

`g:html_indent_tags` is used to define custom tags you want indent occurs.
`g:html_exclude_tags` will remove indent define. But only on default defines.
Means `g:html_indent_tags` will overwrite `g:html_exclude_tags`

**Comment by amadeus** [comment]
ahh, thanks!
