### ISSUE TITLE
vim74 unknow function: htmlcomplete#DetectOmniFlavor

### ISSUE THREAD

**Issue by xqin** [othree/html5.vim#61]
Error Message:
![image](https://cloud.githubusercontent.com/assets/1265888/7342083/d347f9e6-ece0-11e4-85f7-a1d07fe7d12f.png)

Vim version
![ver](https://cloud.githubusercontent.com/assets/1265888/7342138/9afb4c0e-ece1-11e4-8dee-7aab090d36a7.png)

`:script`
![script](https://cloud.githubusercontent.com/assets/1265888/7342140/a0ce1d82-ece1-11e4-861e-3fb8e1e40a88.png)

**Comment by othree** [comment]
Could you execute `:echo &rtp` in Vim.
And see is `/data/.vim/bundle/html5` is in the list?
