### ISSUE TITLE
Syntax highligting not working for custom single word html5 tags

### ISSUE THREAD

**Issue by pmcode** [othree/html5.vim#63]
Unfortunately this fix(https://github.com/othree/html5.vim/issues/54) only solves the problem partially. It still not working for custom "single word" thml5 tags. [Examples](https://angular-ui.github.io/bootstrap/#/tabs) (see pagination, tabs, progressbar etc directives)
Could you please fix this issue.

**Comment by othree** [comment]
Based on the [draft](https://w3c.github.io/webcomponents/spec/custom/#concepts)
A custom element identifier must contains a `-`.

**Comment by pmcode** [comment]
That's true. But i think the syntastic (or any other html linter) should warn about invalid markup.
Ок, if you think that the improper html5 tags should not be highlighted the same as regular... perhaps its make sense. But, please, indent them. ALL tags must be properly indented.

p/s. Look at the other IDE-like text editors (ST, Atom, Brackets). They are all highlight and indent custom tags properly.

**Comment by othree** [comment]
noend:
    
    base, link, meta, hr, br, wbr, img, embed, param, source, track, area, col, input, keygen, menuitem

omit:

    p, caption, colgroup, tbody, thead, tfoot, tr, td, th, li, dt, dd, rb, rt, rtc, rp, optgroup, option
