### ISSUE TITLE
Indent specific markers

### ISSUE THREAD

**Issue by perrette** [othree/html5.vim#69]
I am using reveal.js and would find it convenient to indent `<session>` markers automatically in vim. Any hint how to achieve that? Thanks!

**Comment by othree** [comment]
It's related to #63, but still don't have time to solve it :)

**Comment by perrette** [comment]
I see. One open issue is probably enough...
Thanks.

unrelated PS: that only one or two courageous people like you went down the hard way of writing github-tracked VIM extension for HTML+js is probably a (pessimistic) precursor sign of the future of vim compared to, say, sublime or Atom, written in more modern language which are maybe easier to customize? Or simply understood by more people, or just benefit from a larger audience and more people able to contribute? But the death of VIM was announced (disproven) many times, so I'll stop there. Thanks for your contribution anyway.

**Comment by othree** [comment]
I don't think Vim will die, because lots of people are still working on terminal. Not always have GUI to work :)

**Comment by othree** [comment]
Maybe fixed, just run several small tests, ref. 5b13cd0a60bcce78df697faf35cdb98606985d44

**Comment by perrette** [comment]
For some reason I still can't get the indentation to work (regardless of additional .vimrc line `let g:html_indent_inctags = "section"`). But maybe that's due to interaction with another option...

Just in case you spot immediately something wrong, here is a stripped-off version of my vimrc:

```
filetype off
syntax on

autocmd FileType html :setlocal sw=2 ts=2 sts=2 " Two spaces for HTML files "
autocmd FileType css :setlocal sw=2 ts=2 sts=2 " Two spaces for CSS files "
autocmd FileType javascript :setlocal sw=2 ts=2 sts=2 " Two spaces for javascript files "

" fix highlighting errors in large files
" May lead to slower files
autocmd BufEnter *html :syntax sync fromstart
autocmd BufEnter *js :syntax sync fromstart

Bundle 'JuliaLang/julia-vim'
Bundle 'vim-scripts/Vim-R-plugin'
Bundle 'ervandew/supertab'
Bundle 'tomtom/tcomment_vim'

Bundle 'othree/html5.vim'

" indent <section> tag (reveal.js)
let g:html_indent_inctags = "section"

Bundle 'hynek/vim-python-pep8-indent'

filetype plugin indent on     " required! 
```

**Comment by perrette** [comment]
PS: sure there is not always a GUI, though I hope HTML developers do have one ! I am more thinking of the choice of VIM as main editor. Just thinking it might have a hard time with modern, well-designed, customizable editors, which work out-of-the-box for a number of common tasks. Only a user's perspective: I am still at vim, but I feel the wind could turn (the main current barrier being: learning to do the same with Sublime, what I already know in VIM - that is not a good reason to use VIM ! This is an intuition anyway, it could also be a round trip back to VIM at the end, never been there to tell)

**Comment by perrette** [comment]
What I mean with indentation, is that given:

```
<section>
<section>
something
</section>
</section>
```
should be automatically indented to:


```
<section>
  <section>
    something
  </section>
</section>
```
(here with TAB = 2 spaces)

**Comment by othree** [comment]
Use `gg=G` to indent entire file for test?

**Comment by perrette** [comment]
Yeah, it looks like:
```
<html ...>
  <head>
    <meta ...>
    ...
    <script>
       This is indented properly.
    </script>
  </head>
  <body>
    <div>
      <p> This looks good. </p>
      <section>
      <h1> This is not indented, why? </h1>
      </section>
    </div>
  </body>
</html>
```

**Comment by othree** [comment]
So it looks well as expected.
Except the `<section>` part.

**Comment by perrette** [comment]
Yes. I wonder why... I attached my minimal .vimrc and test.html.

[minimal_setting.zip](https://github.com/othree/html5.vim/files/109823/minimal_setting.zip)

**Comment by othree** [comment]
How about remove the line

    let g:html_indent_inctags = "section"

**Comment by perrette** [comment]
Niet.

**Comment by perrette** [comment]
Note by the way that having `Bundle 'othree/html5.vim'` or not does not change anything at all...
