### ISSUE TITLE
Aligning attributes

### ISSUE THREAD

**Issue by adriaanzon** [othree/html5.vim#74]
When there are a little too much attributes in a tag, I always like to put them on a new line and have them aligned, like this:

``` html
<div class="container"
     id="mydiv"
     title="foo">

</div>
```

However, when I use `=` to reindent with this plugin, this is wat I get:

``` html
<div class="container"
    id="mydiv"
    title="foo">

</div>
```

The attributes don't get aligned with the attribute on the previous line, they just get indented instead.

I saw that the default html indent file already has a solution for this:
https://github.com/vim/vim/blob/master/runtime/indent/html.vim#L922-L942

**Comment by othree** [comment]
I think the native indent file for html is much more powerful now.
Maybe this one in html.vim is not needed anymore.

**Comment by robertjk** [comment]
I second that. The attribute aligning not only does not work well when auto indenting, but also messes the manually created indentation, when splitting lines.

@othree: The default Vim HTML indentation (with the plugin turned off) works perfectly, so you're probably right.
