### ISSUE TITLE
Add more flexible custom tag naming

### ISSUE THREAD

**Issue by kostacoffee** [othree/html5.vim#81]
Currently, the regex for htmlTagName requires a custom tag to have a dash `-` in it. This is not necessary since custom tags can be written without a dash.

A good regex match would allow for removal of all htmlTagName literals and instead allow the regex to do the work.

**Comment by othree** [comment]
`-` is required

https://www.w3.org/TR/custom-elements/#prod-potentialcustomelementname

**Comment by othree** [comment]
Current regexp is incorrect. I will fix it later.

**Comment by kostacoffee** [comment]
Made a start on this in #80. Just need to add the special characters now.

**Comment by othree** [comment]
#80 is not ok.
You can send another PR if you have a new regexp match the spec.
