### ISSUE TITLE
Highlight problem on '<' and '>' characters

### ISSUE THREAD

**Issue by gabrielps** [othree/html5.vim#84]
I'm having a problem with '<' and '>' characters, as i cant difference where the cursor is. Foreground and background colors are the same.

![cursor-problem](https://cloud.githubusercontent.com/assets/1233288/24010910/7bd1b680-0a79-11e7-9dfd-6636305d5c5f.png)

**Comment by othree** [comment]
I think this is [DoMatchParen](http://vimhelp.appspot.com/pi_paren.txt.html).
And the color comes from your color theme.

**Comment by gabrielps** [comment]
That was it. I disabled MatchParen and the problem went away. Thank you ;)
`let loaded_matchparen = 0`
