### ISSUE TITLE
Partial highlighting of data attributes

### ISSUE THREAD

**Issue by robertjk** [othree/html5.vim#92]
## The problem

`data-*` attributes are highlighted only partially by Vim - only `data` prefix is styled as the other attributes, while the rest of the attribute name is styled like a tag name. For example for attribute `data-target`: `data` would be styled like attribute name, while `-target` like a tag name.

## Expected behavior

I expect the whole attribute name (`data-target` in the example) to be highlighted (styled) as attribute name.

**Comment by othree** [comment]
Hi

I don't see tihs issue

<img width="339" alt="2018-03-07 6 19 43" src="https://user-images.githubusercontent.com/16474/37087044-25fd425a-2234-11e8-810c-2545bd4a92d5.png">

Do you update to latest version?

**Comment by robertjk** [comment]
My mistake. It's actually caused by plugin [vim-javascript](https://github.com/pangloss/vim-javascript). As soon as I disable that plugin, the highlighting works fine. For some reason they don't play well in that area.

**Comment by robertjk** [comment]
I created [issue](https://github.com/nanotech/jellybeans.vim) for that on *vim-javascript*.
