### ISSUE TITLE
b tag bug

### ISSUE THREAD

**Issue by ByteRogue** [othree/html5.vim#95]
I use VueBootstrap, and there all tags starts with 'b-something', so parser recognize it as 'b' tag, resulting that text inside tag is bold. I wonder if you could fix this :)

Thanks

**Comment by othree** [comment]
This is default behavior from [Vim runtime](https://github.com/vim/vim/blob/master/runtime/syntax/html.vim#L271).
I think you can add oneline in vimrc to disable it:

```
let g:html_no_rendering = 1
```

**Comment by ByteRogue** [comment]
Yup that solved problem partially. I guess I’ll have to report bug there
