### ISSUE TITLE
lit-html string templating stops highlighting 

### ISSUE THREAD

**Issue by dman777** [othree/html5.vim#96]
I can't check the version of html5 plugin(don't know how) but I installed it with Vundle about two months ago. 

I am using Polymer 3 which uses html templates. The highlighting does not hightlight because of the templating. Any ideas how to fix? 

![pic1](https://user-images.githubusercontent.com/887815/43993921-32541c12-9d5a-11e8-95e8-47269b72c616.png)

**Comment by othree** [comment]
Hi
This plungin only works when filetype=html
And an polymer component is javascript
So you need other plugin to help
You can try this https://github.com/cdata/vim-tagged-template
I didn't tried before.
It will be great if you can tell me the result.

**Comment by dman777** [comment]
Thanks for the reply! 

Result is horrible for  https://github.com/cdata/vim-tagged-template. It lacks the syntax objects that `vim-javascript` has for themeing and coloring. Also, indention is non working.

Instead, effort is being focused on [ jonsmithers/vim-html-template-literals](https://github.com/jonsmithers/vim-html-template-literals/issues/3#issuecomment-412355075)

**Comment by othree** [comment]
Looks like jonsmithers/vim-html-template-literals already works great?
Close this issue for now.
If there is still something I can improve.
Please let me know.
